# Generated by Django 5.2.1 on 2025-05-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_straum_url_onlinetrack_stram_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinetrack',
            old_name='stram_url',
            new_name='stream_url',
        ),
    ]
