# Generated by Django 5.2.1 on 2025-05-23 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_stram_url_onlinetrack_stream_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='onlinetrack',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.genre'),
        ),
        migrations.AlterField(
            model_name='onlinetrack',
            name='tags',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.onlinetrack')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='music.playlist')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('playlist', 'track', 'online_track'), name='unique_playlist_track_combination')],
            },
        ),
    ]
